apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/v1.2.1/manifests/install.yaml
  
patches:  
  - path: https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/v1.1.1/catalog/install.yaml
    target:
      kind: ConfigMap
      name: argocd-notifications-cm

  - path: telegram-configmap.yaml
    target:
      kind: ConfigMap
      name: argocd-notifications-cm

  - path: telegram-secret.yaml
    target:
      kind: Secret
      name: argocd-notifications-secret