apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argocd
  name: argocd-notifications-cm
data:
  service.telegram: |
    token: $telegram-token
  subscriptions: |
    - recipients:
      - telegram:Argo Cd Notifications
      triggers:
      - on-sync-status-unknown
      - on-sync-failed
      - on-health-degraded
      - on-deployed
