apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: message-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: -1001541434902
    notifications.argoproj.io/subscribe.on-deployed.telegram: -1001541434902
    notifications.argoproj.io/subscribe.on-sync-failed.telegram: -1001541434902
    notifications.argoproj.io/subscribe.on-sync-running.telegram: -1001541434902
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/muhammad-asn/message-app'
    path: deployments-argoapp
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-argoapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
